# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimediaWidgets
from PyQt5.QtGui import QMovie, QIcon, QFont, QPixmap, QImage
from PyQt5.QtMultimedia import QCamera, QCameraInfo, QCameraImageCapture
from PyQt5.QtCore import Qt, QThread, QTimer, pyqtSignal
from PyQt5.QtSerialPort import QSerialPortInfo
import serial
import numpy as np
import pyqtgraph as pg
from VitalProcess import DataProcessingThread
from cloudconnect import MqttConnect
from openpose.sleepPose import sleepPoseEst
from openpose.libSVM import LibSVM

import threading
import os

QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
from pyqtgraph import PlotWidget


# UI界面绘制
class Ui_Form(object):
    # 参数配置
    CLIport = {}
    Dataport = {}
    Osa_signal = pyqtSignal(int)

    # def __init__(self):
    #     # 云端连接线程创建
    #     self.cloud = MqttConnect()
    #     # 线程启动
    #     self.cloud.start(QThread.TimeCriticalPriority)

    def setupUi(self, Form):
        # Form
        Form.setObjectName("Form")
        Form.resize(603, 491)

        # BreathingWaveform
        self.BreathingWaveform = PlotWidget(Form)
        self.BreathingWaveform.setBackground(None)
        self.BreathingWaveform.setGeometry(QtCore.QRect(40, 110, 211, 161))
        self.BreathingWaveform.setTitle("Breathing Waveform", color=0x008080, size='8pt')
        self.BreathingWaveform.setXRange(0, 250)
        self.BreathingWaveform.setYRange(-2, 2)
        font = QFont('Times New Roman')
        self.BreathingWaveform.setFont(font)
        styles = {'color': 'b', 'font-size': '9px'}
        self.BreathingWaveform.setLabel('left', text='Position (mm)', **styles)
        self.BreathingWaveform.setLabel('bottom', text='Time (pre 50ms)', **styles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreathingWaveform.sizePolicy().hasHeightForWidth())
        self.BreathingWaveform.setSizePolicy(sizePolicy)
        self.BreathingWaveform.setObjectName("BreathingWaveform")

        # label_9
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(170, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        # CardiacWaveform
        self.CardiacWaveform = PlotWidget(Form)
        self.CardiacWaveform.setBackground(None)
        self.CardiacWaveform.setGeometry(QtCore.QRect(40, 280, 211, 161))
        self.CardiacWaveform.setTitle("Cardiac Waveform", color=0x008080, size='8pt')
        self.CardiacWaveform.setXRange(0, 250)
        self.CardiacWaveform.setYRange(-2, 2)
        styles = {'color': 'b', 'font-size': '9px'}
        self.CardiacWaveform.setLabel('left', text='Position (mm)', **styles)
        self.CardiacWaveform.setLabel('bottom', text='Time (pre 50ms)', **styles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardiacWaveform.sizePolicy().hasHeightForWidth())
        self.CardiacWaveform.setSizePolicy(sizePolicy)
        self.CardiacWaveform.setObjectName("CardiacWaveform")

        # label
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 50, 74, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.label.setFont(font)
        self.label.setObjectName("label")

        # openPushButton
        self.openPushButton = QtWidgets.QPushButton(Form)
        self.openPushButton.setGeometry(QtCore.QRect(180, 80, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPushButton.sizePolicy().hasHeightForWidth())
        self.openPushButton.setSizePolicy(sizePolicy)
        self.openPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cabin Sketch")
        font.setPointSize(7)
        self.openPushButton.setFont(font)
        self.openPushButton.setObjectName("openPushButton")
        self.openPushButton.clicked.connect(self.on_openPushButton_clicked)

        # cfgComboBox
        self.cfgComboBox = QtWidgets.QComboBox(Form)
        self.cfgComboBox.setGeometry(QtCore.QRect(120, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(8)
        self.cfgComboBox.setFont(font)
        self.cfgComboBox.setObjectName("cfgComboBox")

        # refreshPushButton
        self.refreshPushButton = QtWidgets.QPushButton(Form)
        self.refreshPushButton.setGeometry(QtCore.QRect(180, 50, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshPushButton.sizePolicy().hasHeightForWidth())
        self.refreshPushButton.setSizePolicy(sizePolicy)
        self.refreshPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cabin Sketch")
        font.setPointSize(7)
        self.refreshPushButton.setFont(font)
        self.refreshPushButton.setObjectName("refreshPushButton")
        self.refreshPushButton.clicked.connect(self.on_refreshPushButton_clicked)

        # label_2
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(31, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        # dataComboBox
        self.dataComboBox = QtWidgets.QComboBox(Form)
        self.dataComboBox.setGeometry(QtCore.QRect(120, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(8)
        self.dataComboBox.setFont(font)
        self.dataComboBox.setObjectName("dataComboBox")

        # startPushButton
        self.startPushButton = QtWidgets.QPushButton(Form)
        self.startPushButton.setGeometry(QtCore.QRect(230, 50, 21, 21))
        self.startPushButton.setText("")
        self.startPushButton.setObjectName("startPushButton")
        path = os.path.dirname(__file__)
        self.startPushButton.setIcon(QIcon(path+"/image/start.png"))
        self.startPushButton.clicked.connect(self.on_startPushButton_clicked)

        # stopPushButton
        self.stopPushButton = QtWidgets.QPushButton(Form)
        self.stopPushButton.setGeometry(QtCore.QRect(230, 80, 21, 21))
        self.stopPushButton.setText("")
        self.stopPushButton.setObjectName("stopPushButton")
        path = os.path.dirname(__file__)
        self.stopPushButton.setIcon(QIcon(path+"/image/stop.png"))
        self.stopPushButton.clicked.connect(self.on_stopPushButton_clicked)

        # breathLcdNumber
        self.breathLcdNumber = QtWidgets.QLCDNumber(Form)
        self.breathLcdNumber.setGeometry(QtCore.QRect(450, 140, 131, 31))
        self.breathLcdNumber.setObjectName("breathLcdNumber")

        # label_10
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(450, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        # emergy_label
        self.emerge_label = QtWidgets.QLabel(Form)
        self.emerge_label.setGeometry(QtCore.QRect(450, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.emerge_label.setFont(font)
        self.emerge_label.setObjectName("emerge_label")
        self.emerge_label.setStyleSheet('color:green;')
        self.emerge_label.setText("Safe")

        # state_label
        self.state_label = QtWidgets.QLabel(Form)
        self.state_label.setGeometry(QtCore.QRect(40, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.state_label.setFont(font)
        self.state_label.setObjectName("state_label")
        self.state_label.setStyleSheet('color:#00557f;')
        self.state_label.setText("State:")
        # motion_label
        self.motion_label = QtWidgets.QLabel(Form)
        self.motion_label.setGeometry(QtCore.QRect(120, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.motion_label.setFont(font)
        self.motion_label.setObjectName("motion_label")

        # osa_label
        self.osa_label = QtWidgets.QLabel(Form)
        self.osa_label.setGeometry(QtCore.QRect(280, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.osa_label.setFont(font)
        self.osa_label.setObjectName("osa_label")
        self.osa_label.setStyleSheet('color:red;')
        self.osa_label.setText("OSA:")

        # osaLcdNumber
        self.osaLcdNumber = QtWidgets.QLCDNumber(Form)
        self.osaLcdNumber.setGeometry(QtCore.QRect(320, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(False)
        font.setWeight(50)
        self.osaLcdNumber.setFont(font)
        self.osaLcdNumber.setObjectName("osaLcdNumber")

        # heartLcdNumber
        self.heartLcdNumber = QtWidgets.QLCDNumber(Form)
        self.heartLcdNumber.setGeometry(QtCore.QRect(450, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(False)
        font.setWeight(50)
        self.heartLcdNumber.setFont(font)
        self.heartLcdNumber.setObjectName("heartLcdNumber")

        # lebel_11
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(450, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        # label_8
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 41, 31))
        self.label_8.setObjectName("label_8")
        path = os.path.dirname(__file__)
        self.pixmap = QPixmap(path+'/image/lifeline-in-a-heart-outline.png')
        self.label_8.setPixmap(self.pixmap)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(Qt.AlignCenter)

        # camera
        self.camera = QtWidgets.QLabel(Form)
        self.camera.setGeometry(QtCore.QRect(280, 230, 301, 211))
        self.camera.setObjectName("camera")

        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 190, 221, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # label_6
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        # cameraComboBox
        self.cameraComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cameraComboBox.setObjectName("cameraComboBox")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.cameraComboBox.setFont(font)
        self.horizontalLayout_2.addWidget(self.cameraComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        # cameraPushButton
        self.cameraPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cameraPushButton.setMaximumSize(QtCore.QSize(22, 22))
        self.cameraPushButton.setStyleSheet("background-color:transparent;")
        path = os.path.dirname(__file__)
        self.cameraPushButton.setIcon(QIcon(path+'/image/yes.png'))
        self.cameraPushButton.setText("")
        self.cameraPushButton.setFont(font)
        self.cameraPushButton.setFlat(True)
        self.cameraPushButton.setObjectName("cameraPushButton")
        self.cameraPushButton.clicked.connect(self.on_cameraPushButton_clicked)
        self.horizontalLayout_2.addWidget(self.cameraPushButton)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 3)

        # cameraCloseButton
        self.cameraCloseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cameraCloseButton.setMaximumSize(QtCore.QSize(22, 22))
        self.cameraCloseButton.setStyleSheet("background-color:transparent;")
        path = os.path.dirname(__file__)
        self.cameraCloseButton.setIcon(QIcon(path + '/image/false.png'))
        self.cameraCloseButton.setText("")
        self.cameraCloseButton.setFont(font)
        self.cameraCloseButton.setFlat(True)
        self.cameraCloseButton.setObjectName("cameraCloseButton")
        self.cameraCloseButton.clicked.connect(self.on_cameraCloseButton_clicked)
        self.horizontalLayout_2.addWidget(self.cameraCloseButton)


        # label_7
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        # positionLabel
        self.positionLabel = QtWidgets.QLabel(Form)
        self.positionLabel.setGeometry(QtCore.QRect(280, 70, 141, 101))
        self.positionLabel.setWordWrap(False)
        self.positionLabel.setObjectName("positionLabel")
        path = os.path.dirname(__file__)
        self.movie = QMovie(path+'/image/loading1.gif')
        self.positionLabel.setMovie(self.movie)
        self.positionLabel.setScaledContents(False)
        self.movie.start()
        self.positionLabel.setAlignment(Qt.AlignCenter)
        self.positionLabel.show()

        # pose image导入
        self.pixmap0 = QPixmap('D:/Desktop Files/Vital_Monitor/image/up.png')
        self.pixmap1 = QPixmap('D:/Desktop Files/Vital_Monitor/image/down.png')
        self.pixmap2 = QPixmap('D:/Desktop Files/Vital_Monitor/image/left.png')
        self.pixmap3 = QPixmap('D:/Desktop Files/Vital_Monitor/image/left_up.png')
        self.pixmap4 = QPixmap('D:/Desktop Files/Vital_Monitor/image/left_down.png')
        self.pixmap5 = QPixmap('D:/Desktop Files/Vital_Monitor/image/right.png')
        self.pixmap6 = QPixmap('D:/Desktop Files/Vital_Monitor/image/right_up.png')
        self.pixmap7 = QPixmap('D:/Desktop Files/Vital_Monitor/image/right_down.png')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Vital Sign Monitor"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Vital Sign Monitor</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">CFG_PORT：</span></p></body></html>"))
        self.openPushButton.setText(_translate("Form", "Open"))
        self.refreshPushButton.setText(_translate("Form", "Refresh"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Data_PORT：</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">Heart Rate：</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff5500;\">Breath Rate：</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p>Camera：</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>Position</p></body></html>"))

    # 串口刷新
    def on_refreshPushButton_clicked(self):
        # 清空串口名
        self.cfgComboBox.clear()
        self.dataComboBox.clear()

        # 遍历串口信息
        for info in QSerialPortInfo.availablePorts():
            self.cfgComboBox.addItem(info.portName())
            self.dataComboBox.addItem(info.portName())

    # 串口初始化
    def setup_serialPort(self):
        self.on_refreshPushButton_clicked()

    def on_openPushButton_clicked(self):
        # 串口开启函数
        self.CLIport = serial.Serial()
        self.CLIport.port = self.cfgComboBox.currentText()
        self.CLIport.baudrate = 115200
        # self.CLIport = serial.Serial(self.cfgComboBox.currentText(), 115200)
        self.CLIport.open()

        if self.CLIport.isOpen():
            print("CLI串口打开成功!\n")
        else:
            print("CLI串口打开失败！！！\n")

        self.Dataport = serial.Serial()
        self.Dataport.port = self.dataComboBox.currentText()
        self.Dataport.baudrate = 921600
        # self.Dataport = serial.Serial(self.dataComboBox.currentText())
        self.Dataport.open()

        if self.Dataport.isOpen():
            print("Data串口打开成功!\n")
        else:
            print("Data串口打开失败！！！\n")

    def on_startPushButton_clicked(self):
        self.start_time = time.time()
        self.apnea_count = 0
        self.osaLcdNumber.display(self.apnea_count)
        # 信号处理线程创建
        self.ProcessThread = DataProcessingThread(self.CLIport, self.Dataport)
        # 线程启动
        self.ProcessThread.start(QThread.InheritPriority)

        # 连接信号与槽函数
        self.ProcessThread.breath_rate_signal.connect(self.update_breath_rate)
        # self.ProcessThread.breath_rate_signal.connect(self.cloud.publish_breathRate)
        self.ProcessThread.heart_rate_signal.connect(self.update_heart_rate)
        # self.ProcessThread.heart_rate_signal.connect(self.cloud.publish_heartRate)

        self.ProcessThread.breath_energy_signal.connect(self.update_breath_energy)

        self.ProcessThread.motion_signal.connect(self.update_motion)

        self.ProcessThread.breath_wave_signal.connect(self.update_breath_wave)
        self.ProcessThread.heart_wave_signal.connect(self.update_heart_wave)

    def update_breath_wave(self, breathOut):
        self.BreathingWaveform.clear()
        # 数据更新
        self.ProcessThread.Breathsignal.append(breathOut)
        if len(self.ProcessThread.Breathsignal) > 250:
            self.ProcessThread.Breathsignal.pop(0)
        # 波形绘制
        pencil = pg.mkPen(width=2, color='r')
        breathWave = self.BreathingWaveform.plot([], [], pen=pencil)
        breathWave.setData(np.array((list(range(0, 250)), self.ProcessThread.Breathsignal)).T)

    def update_heart_wave(self, heartOut):
        self.CardiacWaveform.clear()
        # 数据更新
        self.ProcessThread.Heartbeatsignal.append(heartOut)
        if len(self.ProcessThread.Heartbeatsignal) > 250:
            self.ProcessThread.Heartbeatsignal.pop(0)
        # 波形绘制
        pencil = pg.mkPen(width=2, color='r')
        heartWave = self.CardiacWaveform.plot([], [], pen=pencil)
        heartWave.setData(np.array((list(range(0, 250)), self.ProcessThread.Heartbeatsignal)).T)

    def update_breath_rate(self, rate):
        self.breathLcdNumber.display(int(rate))

    def update_heart_rate(self, rate):
        self.heartLcdNumber.display(int(rate))

    def update_motion(self, flag):
        if flag == 0:
            self.motion_label.setStyleSheet('color:#005500;')
            self.motion_label.setText("Rest")
        else:
            self.motion_label.setStyleSheet('color:red;')
            self.motion_label.setText("Motion")

    count1 = 0
    count2 = 0

    def update_breath_energy(self, energy):
        self.now_time = time.time()
        interval = self.now_time - self.start_time
        # 增加interval进行起始态呼吸暂停状况排除
        if energy < 150000000 and interval > 8:
            # 初次
            if self.count1 == 0:
                # 记录呼吸暂停开始时间
                self.apnea_start = time.time()

            str = "疑似呼吸暂停！！！"
            self.count1 = self.count1 + 1
            if self.count1 > 5:
                self.count2 = 0
                print(str+"\n")
                self.emerge_label.setStyleSheet('color:red;')
                self.emerge_label.setText("Emergency!")
                self.breathLcdNumber.display(0)
                self.ProcessThread.vitalsign["breathingRateEst_FFT"] = 0
        else:
            # 初次
            if self.count2 == 0 and self.count1 > 5:
                self.apnea_stop = time.time()
                self.apnea_duration = self.apnea_stop - self.apnea_start
                if self.apnea_duration > 9:
                    self.apnea_count = self.apnea_count + 1
                    self.osaLcdNumber.display(self.apnea_count)

            self.count2 = self.count2 + 1
            if self.count2 >= 10:
                self.count1 = 0
                self.emerge_label.setStyleSheet('color:green;')
                self.emerge_label.setText("Safe")
        # 上报暂停次数
        # self.cloud.publish_osa(self.apnea_count)


    def on_stopPushButton_clicked(self):
        # if self.cloud.isRunning():
        #     self.cloud.stop()
        if self.ProcessThread.isRunning():
            self.ProcessThread.stop()
        # 关闭雷达
        self.CLIport.write(('sensorStop\n').encode())
        # 关闭串口
        self.CLIport.close()
        self.Dataport.close()

    def setup_camera_comboBox(self):
        # 获取当前可用的摄像头设备列表
        info_list = QCameraInfo.availableCameras()
        # 将可用摄像头设备名称添加到下拉框中
        for camera_info in info_list:
            self.cameraComboBox.addItem(camera_info.description())
        # 设置下拉框的默认选中项为第一个摄像头设备
        self.cameraComboBox.setCurrentIndex(0)
        # 获取选中的摄像头名称
        selected_camera_info = info_list[self.cameraComboBox.currentIndex()]
        # 使用这个 QCameraInfo 对象来初始化一个新的 QCamera 对象
        self.mycamera = QCamera(selected_camera_info)

    def on_cameraPushButton_clicked(self):
        # 摄像头选择槽函数
        # 获取当前选择的摄像头信息
        info_list = QCameraInfo.availableCameras()
        index = self.cameraComboBox.currentIndex()
        # DSHOW可以解决相机启动慢的问题
        self.mycamera = cv2.VideoCapture(index, cv2.CAP_DSHOW)
        self.ret, self.frame = self.mycamera.read()
        # cv2.imshow("Camera", self.frame)

        # 检查摄像头是否成功打开
        if not self.mycamera.isOpened():
            print("Error: Camera could not be opened")
            return

        # 启动姿态识别线程
        self.poseProcess = sleepPoseEst(self.frame)
        self.poseProcess.start()
        self.poseProcess.pose_tag.connect(self.poseDisplay)

        self.startCameraView()

    def startCameraView(self):
        # 从摄像头读取帧
        self.ret, self.frame = self.mycamera.read()
        if self.ret:
            if hasattr(self, 'poseProcess') and self.poseProcess.isRunning():
                self.poseProcess.readImage(self.frame)
            else:
                print("Pose process is not running.")
            # 转换图像格式以适配Qt显示
            image = self.convertCvQImage(self.frame)
            image = image.scaled(self.camera.width(), self.camera.height())
            # 显示图像
            self.camera.setPixmap(QPixmap.fromImage(image))

        # 使用定时器每一定时间刷新图像
        self.cameraTimer = QTimer()
        self.cameraTimer.singleShot(30, self.startCameraView)  # 约33ms，即10FPS


    def convertCvQImage(self, cv_img):
        """Convert cv::Mat to QImage."""
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QImage(rgb_image.data, w, h, bytes_per_line, QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(640, 480, Qt.KeepAspectRatio)  # You can adjust the resize
        return p

    def poseDisplay(self, pose):
        self.positionLabel.setAlignment(Qt.AlignCenter)
        if pose == 0:
            self.positionLabel.setPixmap(self.pixmap0)
        elif pose == 1:
            self.positionLabel.setPixmap(self.pixmap1)
        elif pose == 2:
            self.positionLabel.setPixmap(self.pixmap5)
        elif pose == 3:
            self.positionLabel.setPixmap(self.pixmap6)
        elif pose == 4:
            self.positionLabel.setPixmap(self.pixmap7)
        elif pose == 5:
            self.positionLabel.setPixmap(self.pixmap2)
        elif pose == 6:
            self.positionLabel.setPixmap(self.pixmap3)
        elif pose == 7:
            self.positionLabel.setPixmap(self.pixmap4)
        # self.cloud.publish_pose(pose)

    def on_cameraCloseButton_clicked(self):
        # self.mycamera.stop()
        # self.view_finder.close()
        # 停止摄像头捕获
        if hasattr(self, 'mycamera') and self.mycamera.isOpened():
            self.mycamera.release()

        # 关闭所有OpenCV创建的窗口
        cv2.destroyAllWindows()

        # 停止用于刷新摄像头画面的定时器
        if hasattr(self, 'cameraTimer'):
            self.cameraTimer.stop()
            self.cameraTimer.deleteLater()

        # 隐藏或删除用于显示摄像头画面的QLabel
        if hasattr(self, 'cameraLabel'):
            self.camera.hide()

        if self.poseProcess.isRunning():
            self.poseProcess.stop()

        # 打印关闭成功的信息
        print("Camera has been closed and resources have been cleaned up.")


